name: Build Live Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install live-build
      run: sudo apt-get update && sudo apt-get install -y live-build

    - name: Configure live-build
      run: lb config -d bullseye --debian-installer none --archive-areas "main contrib non-free" --debootstrap-options "--variant=minbase"

    - name: Build live image
      run: sudo lb build
