name: Build Debian Live with Custom Kernel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install necessary dependencies
      - name: Install Dependencies
        run: |
          lb config --binary-images iso-hybrid --mode debian -d bookworm -a amd64 -k amd64 --linux-packages "linux-image linux-headers" --archive-areas "main contrib non-free non-free-firmware" --cache true --apt-recommends true --debian-installer live --debian-installer-gui true --win32-loader false --bootappend-live "boot=live components live-config.locales=en_GB.UTF-8 live-config.timezone=Europe/London live-config.keyboard-layouts=gb live-config.user-default-groups=cdrom,floppy,audio,video,plugdev,netdev,dialout" --iso-application "Debian Bookworm" --iso-preparer "Dai Trying" --iso-publisher "Dai Trying" --image-name "DaiOs" --mirror-binary http://192.168.1.17/debian/ --mirror-binary-security http://192.168.1.17/debian-security/ --mirror-bootstrap http://192.168.1.17/debian/ --mirror-chroot-security http://192.168.1.17/debian-security/

          #~ Standard entries for creating Live Image.
          echo "live-boot" > config/package-lists/live.list.chroot
          echo "live-config" >> config/package-lists/live.list.chroot
          echo "live-config-systemd" >> config/package-lists/live.list.chroot
          
          #~ Ensure I have all grub packages to allow booting "bios" or "uefi".
          echo grub-common grub2-common grub-pc-bin efibootmgr grub-efi-amd64 grub-efi-amd64-bin grub-efi-amd64-signed grub-efi-ia32-bin libefiboot1 libefivar1 mokutil shim-helpers-amd64-signed shim-signed-common shim-unsigned > config/package-lists/grubuefi.list.binary
          
          #~ My personal selection of packages, here you can modify to your own preference.
          if [ ! -f config/packages.lists/desktop.list.chroot ]; then
            echo "xfce4 \
            amd64-microcode \
            bash-completion \
            command-not-found \
            conky-all \
            curl \
            filezilla \
            firmware-linux \
            firmware-linux-free \
            firmware-linux-nonfree \
            firmware-misc-nonfree \
            galculator \
            geany \
            gparted \
            hardinfo \
            intel-microcode \
            inxi \
            lightdm \
            mc \
            meld \
            mpv \
            network-manager-gnome \
            openssh-client \
            rsync  \
            simplescreenrecorder \
            synaptic \
            terminator \
            wget \
            xfce4-goodies \
            xfce4-terminal" > config/package-lists/desktop.list.chroot
          fi
          
          #~ Build the image.
          sudo lb build
