name: Build Live Image with Custom Kernel and Initrd

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        sudo apt-get install -y build-essential fakeroot libncurses5-dev libssl-dev ccache bison flex libelf-dev libudev-dev libpci-dev libiberty-dev debhelper dpkg-dev debootstrap gpg debian-archive-keyring
        
        wget https://ftp.debian.org/debian/pool/main/l/live-build/live-build_20240810_all.deb
        sudo dpkg -i live-build_20240810_all.deb

    # ... (previous steps remain unchanged)

    - name: Configure live-build for Debian with Custom Kernel and Initrd
      run: |
        mkdir -p live-build
        cd live-build
        
        # Initialize live-build configuration
        lb config --distribution bookworm --archive-areas "main contrib non-free non-free-firmware" --debian-installer none
        
        # Create necessary directories
        mkdir -p config/packages.chroot config/package-lists config/hooks/normal config/includes.chroot/etc/default

        # Copy custom kernel .deb files to live-build package directory
        cp ../custom-kernel-debs/*.deb config/packages.chroot/
        
        # Copy custom initrd to live-build package directory
        cp ../initrd.img-6.10.7-custom config/packages.chroot/
        
        # Create package list
        cat << EOF > config/package-lists/my.list.chroot
        efivar
        efibootmgr
        grub-efi-amd64
        linux-image-amd64
        linux-firmware
        EOF
        
        # Create GRUB default configuration
        echo 'GRUB_TIMEOUT=5' > config/includes.chroot/etc/default/grub
        
        # Create a hook to install custom kernel, update initramfs, and install grub-pc
        cat << EOF > config/hooks/normal/0100-update-initramfs.hook.chroot
        #!/bin/sh
        set -e
        
        # Update package lists
        apt-get update
        
        # Install the custom kernel
        dpkg -i /config/packages.chroot/linux-image-6.10.7_*.deb
        
        # Update initramfs for the new kernel
        update-initramfs -c -k 6.10.7
        
        # Install grub-pc after initial setup
        apt-get install -y grub-pc
        
        # Update GRUB configuration
        update-grub
        EOF
        
        chmod +x config/hooks/normal/0100-update-initramfs.hook.chroot

    # ... (remaining steps unchanged)
