name: Build Live Image with Custom Kernel and Initrd

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        sudo apt-get install -y build-essential fakeroot libncurses5-dev libssl-dev ccache bison flex libelf-dev libudev-dev libpci-dev libiberty-dev debhelper dpkg-dev debootstrap gpg debian-archive-keyring
        
        wget https://ftp.debian.org/debian/pool/main/l/live-build/live-build_20240810_all.deb
        sudo dpkg -i live-build_20240810_all.deb
    - name: Download and Compile Custom Kernel
      run: |
          KERNEL_VERSION=6.10.7
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${KERNEL_VERSION}.tar.xz
          tar -xvf linux-${KERNEL_VERSION}.tar.xz
          cd linux-${KERNEL_VERSION}
          make defconfig
          sed -i 's/# CONFIG_IPU_BRIDGE is not set/CONFIG_IPU_BRIDGE=y/' .config
          sed -i 's/# CONFIG_VIDEO_INTEL_IPU6 is not set/CONFIG_VIDEO_INTEL_IPU6=y/' .config
          sed -i 's/# CONFIG_INTEL_VSC is not set/CONFIG_INTEL_VSC=y/' .config
          sed -i 's/# CONFIG_VIDEO_IPU3_CIO2 is not set/CONFIG_VIDEO_IPU3_CIO2=y/' .config
          sed -i 's/# CONFIG_VIDEO_ATOMISP is not set/CONFIG_VIDEO_ATOMISP=y/' .config
          sed -i 's/# CONFIG_VIDEO_ATOMISP_OV2722 is not set/CONFIG_VIDEO_ATOMISP_OV2722=y/' .config
          sed -i 's/# CONFIG_VIDEO_ATOMISP_GC2235 is not set/CONFIG_VIDEO_ATOMISP_GC2235=y/' .config
          sed -i 's/# CONFIG_VIDEO_ATOMISP_MSRLIST_HELPER is not set/CONFIG_VIDEO_ATOMISP_MSRLIST_HELPER=y/' .config
          sed -i 's/# CONFIG_VIDEO_ATOMISP_MT9M114 is not set/CONFIG_VIDEO_ATOMISP_MT9M114=y/' .config
          sed -i 's/# CONFIG_VIDEO_ATOMISP_GC0310 is not set/CONFIG_VIDEO_ATOMISP_GC0310=y/' .config
          echo "CONFIG_IPU_BRIDGE=y" >> .config
          echo "CONFIG_VIDEO_INTEL_IPU6=y" >> .config
          echo "CONFIG_INTEL_VSC=y" >> .config
          echo "CONFIG_VIDEO_IPU3_CIO2=y" >> .config
          echo "CONFIG_VIDEO_ATOMISP=y" >> .config
          echo "CONFIG_VIDEO_ATOMISP_OV2722=y" >> .config
          echo "CONFIG_VIDEO_ATOMISP_GC2235=y" >> .config
          echo "CONFIG_VIDEO_ATOMISP_MSRLIST_HELPER=y" >> .config
          echo "CONFIG_VIDEO_ATOMISP_MT9M114=y" >> .config
          echo "CONFIG_VIDEO_ATOMISP_GC0310=y" >> .config
          make -j$(nproc) bindeb-pkg
          # Move the kernel packages to a known location
          mkdir -p ../custom-kernel-debs
          mv ../*.deb ../custom-kernel-debs/
    - name: Create Custom Initrd
      run: |
          KERNEL_VERSION=6.10.7
          
          # Install necessary tools
          sudo apt-get install -y initramfs-tools
          # Create a temporary directory for initrd creation
          mkdir -p custom_initrd
          cd custom_initrd
          # Create the initrd
          sudo mkinitramfs -o ../initrd.img-${KERNEL_VERSION}-custom ${KERNEL_VERSION}-custom
          # Move back to the main directory
          cd ..
    - name: Clean up previous build
      run: sudo lb clean

    - name: Configure live-build for Debian with Custom Kernel and Initrd
      run: |
          mkdir -p live-build/config/packages.chroot
          mkdir -p live-build/config/package-lists
          mkdir -p live-build/config/hooks/normal
          # Copy custom kernel .deb files to live-build package directory
          cp custom-kernel-debs/*.deb live-build/config/packages.chroot/
          # Copy custom initrd to live-build package directory
          cp initrd.img-6.10.7-custom live-build/config/packages.chroot/
          echo "efivar" > live-build/config/package-lists/my.list.chroot
          echo "efibootmgr" >> live-build/config/package-lists/my.list.chroot
          echo "grub-pc" >> live-build/config/package-lists/my.list.chroot
          # Create a hook to install custom kernel and update initramfs
          set -x
          cat << EOF > live-build/config/hooks/normal/0100-update-initramfs.hook.chroot
          #!/bin/sh
          set -e
          set -x
          
          # Install the custom kernel
          dpkg -i /config/packages.chroot/linux-image-6.10.7_*.deb
          
          # Replace the default initrd with our custom one
          cp /config/packages.chroot/initrd.img-6.10.7-custom /boot/initrd.img-6.10.7
          
          # Update GRUB to use the new kernel and initrd
          update-grub
          EOF
          chmod +x live-build/config/hooks/normal/0100-update-initramfs.hook.chroot
          cd live-build    
    
          lb config -d bookworm --debian-installer none --archive-areas "main contrib non-free" \
            --debootstrap-options "--keyring=/usr/share/keyrings/debian-archive-keyring.gpg --variant=minbase"

    - name: Build Debian Live ISO with Custom Kernel and Initrd
      run: |
          cd live-build
          sudo lb build
    - name: Upload Live ISO
      uses: actions/upload-artifact@v3
      with:
          name: debian-live-custom-kernel-initrd.iso
          path: live-build/*.iso
