name: Build Debian Live with Custom Kernel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential fakeroot libncurses5-dev libssl-dev ccache bison flex libelf-dev libudev-dev libpci-dev libiberty-dev debhelper live-build dpkg-dev debootstrap gpg
      # Install necessary dependencies
      - name: lb config
        run: |
          #!/bin/sh

          #This was the default one from /usr/share/doc/live-build/examples/auto
          #I will consider tweaking it later if necessary.

          set -e
          sudo lb config noauto \
          	--distribution bookworm \
          	--architecture amd64 \
          	--debian-installer live \
          	--debian-installer-distribution bookworm \
          	--linux-flavours "amd64" \
          	--archive-areas "main contrib non-free-firmware non-free" \
          	--apt-recommends false \
          	--apt-source-archives true \
          	"${@}"

          #Add more stuff later.
          sudo lb build noauto "${@}"
