name: Build Live Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        sudo apt-get install -y build-essential fakeroot libncurses5-dev libssl-dev ccache bison flex libelf-dev libudev-dev libpci-dev libiberty-dev debhelper dpkg-dev debootstrap gpg debian-archive-keyring
        
        wget https://ftp.debian.org/debian/pool/main/l/live-build/live-build_20240810_all.deb
        sudo dpkg -i live-build_20240810_all.deb

    - name: Configure live-build
      run: lb config -d testing --debian-installer none --archive-areas "main contrib non-free" --debootstrap-options "--keyring=/usr/share/keyrings/debian-archive-keyring.gpg --variant=minbase"

    - name: Build live image
      run: sudo lb build
