name: Build Jammy Live Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Install dependencies
      run: |
        sudo apt-get -y install vim live-build fdisk

    - name: Configure live-build for Debian with Custom Kernel and Initrd
      run: |
        sudo lb config --distribution jammy --debian-installer live --binary-images netboot --debconf-frontend noninteractive --chroot-filesystem squashfs --archive-areas "main restricted universe multiverse" --apt-options "--yes" --bootappend-live "keyboard-layouts=no" --mode ubuntu --firmware-chroot false

    - name: Build Debian Live ISO
      run: |
        sudo lb build

    - name: Check for ISO file
      run: |
        if [ -f live-image-amd64.hybrid.iso ]; then
          echo "ISO file created successfully"
        else
          echo "Error: ISO file not created"
          ls -R
          exit 1
        fi

    - name: Upload Live ISO
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: debian-live-custom-kernel-initrd.iso
        path: live-image-amd64.hybrid.iso

    - name: Clean up
      if: always()
      run: |
         lb clean
         sudo rm -rf chroot
